set runtimepath+=~/.config/vim/bundle/swift.vim
set paste
call plug#begin('~/.config/vim/plugged')
" Make sure you use single quotes
" Shorthand notation; fetches https://github.com/junegunn/vim-easy-align
Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'tpope/vim-fireplace', { 'for': 'clojure' }
Plug 'junegnn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'tpope/vim-fugitive'
Plug 'morhetz/gruvbox'
Plug 'airblade/vim-rooter'
Plug 'jpo/vim-railscasts-theme'
Plug 'udalov/kotlin-vim'

" Initialize plugin system
call plug#end()
" Don't try to be vi compatible
set nocompatible
"
" " Helps force plugins to load correctly when it is turned back on below
filetype off
"
" " TODO: Load plugins here (pathogen or vundle)
"
" " Turn on syntax highlighting
syntax on
"
" " For plugins to load correctly
filetype plugin indent on
"
" " TODO: Pick a leader key
let mapleader = " "
"
" " Security
set modelines=0
"
" " Show line numbers
set number
set cursorline
"
" " Show file stats
map <leader>j :wincmd j<CR>
set ruler
"
" " Blink cursor on error instead of beeping (grr)
set visualbell
"
" " Encoding
set encoding=utf-8
"
" " Whitespace
set wrap
set textwidth=79
set formatoptions=tcqrn1
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab
set noshiftround
"
" " Cursor motion
set scrolloff=3
set backspace=indent,eol,start
set matchpairs+=<:> " use % to jump between pairs
" runtime! macros/matchit.vim
"
" " Move up/down editor lines
nnoremap j gj
nnoremap k gk
"
" " Allow hidden buffers
set hidden
"
" " Rendering
set ttyfast
"
" " Status bar
set laststatus=2
"
" " Last line
set showmode
set showcmd
"
" " Searching
nnoremap / /\v
vnoremap / /\v
set hlsearch
set incsearch
set ignorecase
set smartcase
set showmatch
map <leader><space> :let @/=''<cr> " clear search
"
" " Remap help key.
" inoremap <F1> <ESC>:set invfullscreen<CR>a
" nnoremap <F1> :set invfullscreen<CR>
" vnoremap <F1> :set invfullscreen<CR>
"
" " Textmate holdouts
"
" " Formatting
map <leader>q gqip
"
" " Visualize tabs and newlines
set listchars=tab:▸\ ,eol:¬
" " Uncomment this to enable by default:
set list " To enable by default
" " Or use your leader key + l to toggle on/off
" map <leader>l :set list!<CR> " Toggle tabs and EOL
"
" " Color scheme (terminal)
set t_Co=256
set background=dark
let g:solarized_termcolors=256
let g:solarized_termtrans=1
colorscheme gruvbox

set relativenumber
map <leader>a :Ag<CR>
map <leader>s :Snippets<CR>
map <leader>c :Commits<CR>
map <leader>t :NERDTreeToggle<CR>
map <leader>h :wincmd h<CR>
map <leader>l :wincmd l<CR>
map <leader>j :wincmd j<CR>
map <leader>k :wincmd k<CR>
map <leader>ver :wincmd v<CR>
map <leader>hor :wincmd S<CR>
map <leader>qu :wincmd q<CR>
map <leader>g :wincmd W<CR>
nnoremap <silent> <Leader>b :Buffers<CR>
nnoremap <silent> <Leader>g :Rg<CR>
nnoremap <silent> <Leader>sf :Files<CR>
nnoremap <silent> <Leader>sh :History<CR>
nnoremap <silent> <Leader>sl :BLines<CR>
nnoremap <silent> <Leader>sgl :Lines<CR>
nnoremap <silent> <Leader>fk :q!<CR>
nnoremap <silent> <Leader>wk :wq<CR>
execute pathogen#infect()
let g:NERDTreeDirArrowExpandable = '▸'
let g:NERDTreeDirArrowCollapsible = '▾'
let g:gruvbox_number_column = 'green'

if has('nvim-0.4.0') || has("patch-8.2.0191")
    let g:fzf_layout = { 'window': {
                \ 'width': 0.9,
                \ 'height': 0.7,
                \ 'highlight': 'Comment',
                \ 'rounded': v:false } }
else
    let g:fzf_layout = { "window": "silent botright 16split enew" }
endif


if has("autocmd")
  " Enable file type detection
  filetype on

  " Syntax of these languages is fussy over tabs Vs spaces
  autocmd FileType make setlocal ts=8 sts=8 sw=8 noexpandtab
  autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab

  " Customisations based on house-style (arbitrary)
  autocmd FileType html setlocal ts=2 sts=2 sw=2 expandtab
  autocmd FileType css setlocal ts=2 sts=2 sw=2 expandtab
  autocmd FileType javascript setlocal ts=4 sts=4 sw=4 noexpandtab

  " Treat .rss files as XML
  autocmd BufNewFile,BufRead *.rss setfiletype xml
endif

if has("autocmd") 
  filetype plugin indent on
endif
