#!/usr/bin/env sh

limelight -m config width            1
limelight -m config radius           10
limelight -m config placement        interior
limelight -m config active_color     0xffffa500
limelight -m config normal_color     0xff555555

echo "limelight configuration loaded.."
